# Conexion al docker de posgresql no mover
version: '3.8'

services:
  app:
    build:
      context: ./backend        # carpeta de tu código de aplicación
      dockerfile: Dockerfile
    container_name: cubicanet_app
    env_file:
      - .env                    # carga USER, PASS y DB que ya probaste
    environment:
      - DB_HOST=postgres18beta1 # nombre del contenedor de Postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - FLASK_ENV=development   # o la variable equivalente de tu framework
    volumes:
      - ./backend:/app          # hot-reload en desarrollo
    ports:
      - "8000:8000"
    depends_on:
      - db                      # orden lógico, aunque el servicio db esté externo
    networks:
      - cubicanet

networks:
  cubicanet:
    external: true
#final de la conexion a BD

#backend
app:
  build: .
  env_file: .env
  ports:
    - "8000:8000"
  depends_on:
    - db

